dashboard/config/routes.rb
Dashboard::Application.routes.draw do
  resources :gallery_activities, path: '/gallery' do
    collection do
      get 'art', to: 'gallery_activities#index', app: Game::ARTIST
      get 'apps', to: 'gallery_activities#index', app: Game::PLAYLAB
    end
  end
  resources :activity_hints, only: [:update]
  resources :callouts
  resources :videos do
    collection do
      get 'test'
      get 'embed/:key', to: 'videos#embed', as: 'embed'
    end
  end
  resources :concepts
  resources :activities

  resources :sections do
    member do
      post 'log_in'
    end
  end

  resources :level_sources, path: '/sh/', only: [:show, :edit] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end
  get '/share/:id', to: redirect('/sh/%{id}')

  get '/s/k-1(/*all)', to: redirect('/s/course1')
  get '/s/2-3(/*all)', to: redirect('/s/course2')
  get '/s/4-5(/*all)', to: redirect('/s/course3')

  resources :level_source_hints
  get '/add_hint/:level_source_id', :to => 'level_source_hints#add_hint', as: 'add_hint'
  get '/show_hints/:level_source_id', :to => 'level_source_hints#show_hints', as: 'show_hints'
  get '/add_pop_hint/:idx', :to => 'level_source_hints#add_pop_hint', as: 'add_pop_hint'
  get '/show_pop_hints/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints', as: 'show_pop_hints'
  get '/add_pop_hint_per_level/:level_id/:idx', :to => 'level_source_hints#add_pop_hint_per_level', as: 'add_pop_hint_per_level'
  get '/show_pop_hints_per_level/:level_id/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints_per_level', as: 'show_pop_hints_per_level'
  get '/add_hint_access', :to => 'level_source_hints#add_hint_access', as: 'add_hint_access'

  resources :frequent_unsuccessful_level_sources, only: [:index]

  devise_scope :user do
    get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :levels do
    get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
    post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
    post 'clone', to: 'levels#clone'
  end

  resources :games

  get 'builder', to: 'levels#builder'
  post 'upload_maze_level', to: 'levels#upload_maze_level'
  post 'create_custom', to: 'levels#create_custom'
  get 'levels/new', to: 'levels#new'

  resources :scripts, path: '/s/' do
    post 'sort', to: 'scripts#sort'

    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end

    get 'puzzle/:chapter', to: 'script_levels#show', as: 'puzzle', format: false

    resources :stages, only: [:show], path: "/stage", format: false do
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
      end
    end
  end

  get '/beta', to: 'home#beta', as: 'beta'

  get 'reset_session', to: 'application#reset_session_endpoint'

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, reset:true
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false
  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID.to_s, format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID, as: 'editcode_chapter', format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID.to_s, format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID, as: 'twenty_fourteen_chapter', format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID.to_s, format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID, as: 'builder_chapter', format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID.to_s, format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID, as: 'flappy_chapter', format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID.to_s, format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID, as: 'jigsaw_chapter', format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID.to_s, format: false

  resources :followers, only: [:create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'
  get '/followers/sections', to: 'followers#sections', as: 'sections_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove', to: 'followers#remove', as: 'remove_follower'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/level/:level_id', :to => 'activities#milestone', :as => 'milestone_level'
  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/admin/concepts', to: 'reports#admin_concepts', as: 'admin_concepts'
  get '/admin/gallery', to: 'reports#admin_gallery', as: 'admin_gallery'
  get '/admin/assume_identity', to: 'reports#assume_identity_form', as: 'assume_identity_form'
  post '/admin/assume_identity', to: 'reports#assume_identity', as: 'assume_identity'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'
  get '/api/section_progress/:id', to: 'api#section_progress', as: 'section_progress'
  get '/api/student_progress/:section_id/:id', to: 'api#student_progress', as: 'student_progress'
  get '/api/courses', to: 'api#courses', as: 'courses'

  resources :zendesk_session, only: [:index]

  post '/sms/send', to: 'sms#send_to_phone', as: 'send_to_phone'

end

dashboard/app/controllers/reports_controller.rb
# TODO: reorganize this so it's more obvious which actions are for
# students, teachers, and admins (most likely move into more relevant
# controllers)

class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:header_stats]

  check_authorization except: [:header_stats, :students]

  before_action :set_script
  include LevelSourceHintsHelper

  def user_stats
    @user = User.find(params[:user_id])
    authorize! :read, @user

    #@recent_activity = Activity.where(['user_id = ?', user.id]).order('id desc').includes({level: :game}).limit(2)
    @recent_levels = UserLevel.find_by_sql(<<SQL)
select ul.*, sl.game_chapter, l.game_id, sl.chapter, sl.script_id, sl.id as script_level_id
from user_levels ul
inner join script_levels sl on sl.level_id = ul.level_id
inner join levels l on l.id = ul.level_id
where sl.script_id = 1 and ul.user_id = #{@user.id}
order by ul.updated_at desc limit 2
SQL
  end

  def header_stats
    render file: "shared/_user_stats", layout: false, locals: { user: current_user }
  end

  def prizes
    authorize! :read, current_user
  end

  def usage
    @user = User.find(params[:user_id])
    authorize! :read, @user

    @recent_activities = get_base_usage_activity.where(['user_id = ?', @user.id])
  end

  def all_usage
    authorize! :read, :reports

    @recent_activities = get_base_usage_activity
    render 'usage', formats: [:html]
  end

  def admin_stats
    authorize! :read, :reports
    
    SeamlessDatabasePool.use_persistent_read_connection do
      @user_count = User.count
      @teacher_count = User.where(:user_type => 'teacher').count
      @student_count = @user_count - @teacher_count
      @users_with_teachers = Follower.distinct.count(:student_user_id)
      @users_with_email = User.where('email <> ""').count
      @users_with_confirmed_email = User.where('confirmed_at IS NOT NULL').count
      @girls = User.where(:gender => 'f').count
      @boys = User.where(:gender => 'm').count
 
      @prizes_redeemed = Prize.where('user_id IS NOT NULL').group(:prize_provider).count
      @prizes_available = Prize.where('user_id IS NULL').group(:prize_provider).count
      
      @student_prizes_earned = User.where(:prize_earned => true).count
      @student_prizes_redeemed = Prize.where('user_id IS NOT NULL').count
      @student_prizes_available = Prize.where('user_id IS NULL').count

      @teacher_prizes_earned = User.where(:teacher_prize_earned => true).count
      @teacher_prizes_redeemed = TeacherPrize.where('user_id IS NOT NULL').count
      @teacher_prizes_available = TeacherPrize.where('user_id IS NULL').count
      
      @teacher_bonus_prizes_earned = User.where(:teacher_bonus_prize_earned => true).count
      @teacher_bonus_prizes_redeemed = TeacherBonusPrize.where('user_id IS NOT NULL').count
      @teacher_bonus_prizes_available = TeacherBonusPrize.where('user_id IS NULL').count
    end
  end

  def admin_progress
    authorize! :read, :reports
    
    SeamlessDatabasePool.use_persistent_read_connection do
      @user_count = User.count
      @all_script_levels = Script.twenty_hour_script.script_levels.includes({ level: :game })
 
      @levels_attempted = User.joins(:user_levels).group(:level_id).where('best_result > 0').count
      @levels_attempted.default = 0
      @levels_passed = User.joins(:user_levels).group(:level_id).where('best_result >= 20').count
      @levels_passed.default = 0

      @stage_map = @all_script_levels.group_by { |sl| sl.level.game }
    end
  end

  def admin_concepts
    authorize! :read, :reports
    SeamlessDatabasePool.use_persistent_read_connection do
      render 'admin_concepts', formats: [:html]
    end
  end

  ADMIN_GALLERY_PER_PAGE = 25
  def admin_gallery
    authorize! :read, :reports

    @gallery_activities = GalleryActivity.order(id: :desc).page(params[:page]).per(ADMIN_GALLERY_PER_PAGE)
  end


  def students
    redirect_to teacher_dashboard_url
  end

  def level_stats
    authorize! :read, :reports

    @level = Level.find(params[:level_id])

    best_code_map = Hash.new{|h,k| h[k] = {:level_source_id => k, :count => 0, :popular => false} }
    passing_code_map = Hash.new{|h,k| h[k] = {:level_source_id => k, :count => 0, :popular => false} }
    finished_code_map = Hash.new{|h,k| h[k] = {:level_source_id => k, :count => 0, :popular => false} }
    unsuccessful_code_map = Hash.new{|h,k| h[k] = {:level_source_id => k, :count => 0, :popular => false} }
    all_but_best_code_map = Hash.new{|h,k| h[k] = {:level_source_id => k, :count => 0, :popular => false} }

    Activity.all.where(['level_id = ?', @level.id]).order('id desc').limit(10000).each do |activity|
      # Do not process activity records with nil level_source_id
      if activity.level_source_id.nil?
        next
      end
      if activity.best?
        best_code_map[activity.level_source_id][:count] += 1
      elsif activity.passing?
        passing_code_map[activity.level_source_id][:count] += 1
      elsif activity.finished?
        finished_code_map[activity.level_source_id][:count] += 1
      else
        unsuccessful_code_map[activity.level_source_id][:count] += 1
      end

      if !activity.best?
        all_but_best_code_map[activity.level_source_id][:count] += 1
      end
    end

    # Setting up the popular incorrect code
    if !all_but_best_code_map.empty?
      sorted_all_but_best_code = all_but_best_code_map.values.sort_by {|v| -v[:count] }
      pop_level_source_ids = Array.new([sorted_all_but_best_code.length - 1, 9].min)
      for idx in 0..[sorted_all_but_best_code.length - 1, 9].min
        pop_level_source_id = sorted_all_but_best_code[idx][:level_source_id]
        pop_level_source_ids[idx] = pop_level_source_id
        if passing_code_map.has_key?(pop_level_source_id)
          passing_code_map[pop_level_source_id][:popular] = true
          passing_code_map[pop_level_source_id][:pop_level_source_idx] = idx
        elsif finished_code_map.has_key?(pop_level_source_id)
          finished_code_map[pop_level_source_id][:popular] = true
          finished_code_map[pop_level_source_id][:pop_level_source_idx] = idx
        elsif unsuccessful_code_map.has_key?(pop_level_source_id)
          unsuccessful_code_map[pop_level_source_id][:popular] = true
          unsuccessful_code_map[pop_level_source_id][:pop_level_source_idx] = idx
        end
      end
    end

    @best_code = best_code_map.values.sort_by {|v| -v[:count] }
    @passing_code = passing_code_map.values.sort_by {|v| -v[:count] }
    @finished_code = finished_code_map.values.sort_by {|v| -v[:count] }
    @unsuccessful_code = unsuccessful_code_map.values.sort_by {|v| -v[:count] }
    @pop_level_source_ids = pop_level_source_ids

  end

  def assume_identity_form
    authorize! :manage, :all
  end

  def assume_identity
    authorize! :manage, :all

    user = User.where(:id => params[:user_id]).first
    user ||= User.where(:username => params[:user_id]).first
    user ||= User.find_by_email_or_hashed_email params[:user_id]

    if user
      sign_in user, :bypass => true
      redirect_to '/'
    else
      flash[:error] = "I can't find that user"
      render :assume_identity_form
    end
  end

  private
  def get_base_usage_activity
    Activity.all.order('id desc').includes([:user, :level_source, {level: :game}]).limit(50)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_script
    @script = Script.find(params[:script_id]) if params[:script_id]
  end
end

dashboard/app/helpers/reports_helper.rb
module ReportsHelper
  def bronze_fraction_image_path(completion)
    'bronze_' + [[(completion * 10 / Trophy::BRONZE_THRESHOLD).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  def silver_fraction_image_path(completion)
    'silver_' + [[((completion - Trophy::BRONZE_THRESHOLD) * 10 /
                   (Trophy::SILVER_THRESHOLD - Trophy::BRONZE_THRESHOLD)).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  def gold_fraction_image_path(completion)
    'gold_' + [[((completion - Trophy::SILVER_THRESHOLD) * 10 /
                 (Trophy::GOLD_THRESHOLD - Trophy::SILVER_THRESHOLD)).floor * 10, 100].min, 0].max.to_s + '.png'
  end
  
  def level_passed(params)
    result = 0
    if params[:user]
      result = params[:user_level].best_result if params[:user_level] && params[:user_level].best_result
    elsif (session[:progress] && session[:progress][params[:level_id]])
      result = session[:progress][params[:level_id]]
    end
  
    result >= Activity::MINIMUM_PASS_RESULT
  end
end

dashboard/app/views/reports/_code_groups.html.haml
- if !code_summaries.blank?
  %h4= title
  %table
    %tr
      %th Count
      %th Code
      %th Add Code-Specific Hint
      %th Show Existing Hints
    - code_summaries.each do |result|
      %tr
        %td= result[:count]
        %td= render partial: 'shared/solution', locals: { level_source_id: result[:level_source_id], level: level }
        %td= link_to 'Add Hint', build_add_hint_path(result[:pop_level_source_idx], @pop_level_source_ids) if result[:popular]
        %td= link_to 'Show Hints', show_hints_path(result[:level_source_id]) if result[:popular]

dashboard/app/views/reports/admin_concepts.html.haml
%h1 Admin Concepts progress
:css
  .numeric {
    font-weight: bold;
  }

%h4 Note: Concepts are only implemented for "20-hour" and "Hour of Code" tutorials.

%p
  Total number of concepts at least 20% learned (any trophy):
  %span.numeric= number_with_delimiter UserTrophy.distinct.count('user_id, concept_id')
%p
  Total number of concepts 100% mastered ('Gold' trophy):
  %span.numeric= number_with_delimiter UserTrophy.includes(:trophy).where('trophies.name' => 'gold').count
%p
  Number of users who learned at least 20% of a concept (any trophy):
  %span.numeric= number_with_delimiter UserTrophy.distinct.count('user_id')
%p
  Number of users who 100% mastered at least one concept ('Gold' trophy):
  %span.numeric= number_with_delimiter UserTrophy.includes(:trophy).where('trophies.name' => 'gold').distinct.count('user_id')

%h3= link_to '<< Back to admin stats', admin_stats_path

dashboard/app/views/reports/admin_gallery.html.haml
%h3 Recent drawings that students have saved to their gallery
= paginate @gallery_activities
- @gallery_activities.each do |gallery_activity|
  %div.gallery_activity
    - activity = gallery_activity.activity
    - level_source = activity.level_source
    = link_to image_tag(original_image_level_source_path(level_source)), level_source
    %div.caption
      by
      = activity.user.name
    %div.caption
      = time_ago_in_words activity.created_at
      ago
    %div.caption
      = link_to "delete", gallery_activity_path(gallery_activity), method: :delete, remote: true, class: 'delete-gallery-activity', data: {confirm: 'Are you sure?' }
      
:javascript
  $('.delete-gallery-activity').on('ajax:complete', function(event, xhr, status) {
    $(this).parent().parent().css('opacity', '0.5')
    $(this).replaceWith('<b>Deleted!</b>')
  });

dashboard/app/views/reports/admin_progress.html.haml
%h1 Admin progress

%table
  %tr
    %td{ style: "padding: 0px; vertical-align: top;" }
      %table{ style: "width:150px; table-layout:fixed;"}
        %tr.report_row
          %th{ style: "white-space: nowrap; overflow: hidden; text-overflow:ellipsis;padding-left: 5px;"}= "Signed In Users"
        %tr.report_row{ class: "report_tall_row"}
          %td.fixed_width_cell
            Levels attempted
        %tr.report_row{ class: "report_tall_row"}
          %td.fixed_width_cell
            Levels passed
        %tr.report_row
    %td{ style: "padding: 0px;" }
      %div{ style:"overflow-x:scroll; width: 800px; margin:0px; padding: 0px;" }
        %table{ style:"width:#{@all_script_levels.length * 35}px;table-layout:fixed;"}
          %col{ width: '35px'}
          %tr.report_row
            - @stage_map.each_pair do |game, levels|
              %th{ colspan: levels.length, style: "overflow: hidden;" }= game.name
          %tr.report_row{ class: "report_tall_row"}
            - @all_script_levels.each do |sl|
              - attempt_pct = @levels_attempted[sl.level_id] * 100 / @user_count

              %td{ class: "report_cell", style: "background-color: hsl(#{attempt_pct}, 100%, 40%);" }
                #{attempt_pct}%
          %tr.report_row{ class: "report_tall_row"}
            - @all_script_levels.each do |sl|
              - passed_pct = @levels_passed[sl.level_id] * 100 / @user_count

              %td{ class: "report_cell", style: "background-color: hsl(#{passed_pct}, 100%, 40%);" }
                #{passed_pct}%
          %tr.report_row


%h3= link_to '<< Back to admin stats', admin_stats_path

dashboard/app/views/reports/admin_stats.html.haml
%h1 Admin stats

%h3 Users with accounts

%b Total users
#{@user_count}
%br/
%b Students
#{@student_count}
%br/
%b Teachers
#{@teacher_count}
%br/
%b Gender (when specified):
- if @girls + @boys > 0
  Girls #{@girls * 100 / (@girls + @boys)}% /
  Boys #{@boys * 100 / (@girls + @boys)}%
- else 
  0 users with specified gender
%br/
%b Users linked to a teacher
- if @user_count > 0
  #{@users_with_teachers} (#{@users_with_teachers * 100 / @user_count}%)
- else
  0
%br/
%b Users with an email address
- if @user_count > 0
  #{@users_with_email} (#{@users_with_email * 100 / @user_count}%)
- else 
  0
%br/
%b Teachers with a confirmed email address
- if @teacher_count > 0
  #{@users_with_confirmed_email} (#{@users_with_confirmed_email * 100 / @teacher_count}%)
- else 
  0
%br/
%br/

%h3= link_to 'View Level Progress (slow query) >>', admin_progress_path

%h3= link_to 'View Concept Completions (slow query) >>', admin_concepts_path

%h3 Prizes

%b Total student prizes earned
#{@student_prizes_earned}
%br/
%b Total student prizes redeemed
#{@student_prizes_redeemed}
%br/
- @prizes_redeemed.each do |key, value|
  #{key.name} #{value}
  %br/
%b Student prizes available to be redeemed
#{@student_prizes_available}
%br/
- @prizes_available.each do |key, value|
  #{key.name} #{value}
  %br/
%br/

%b Total teacher prizes earned
#{@teacher_prizes_earned}
%br/
%b Total teacher prizes redeemed
#{@teacher_prizes_redeemed}
%br/
%b Teacher prizes available to be redeemed
#{@teacher_prizes_available}
%br/
%br/

%b Total bonus teacher prizes earned
#{@teacher_bonus_prizes_earned}
%br/
%b Total teacher bonus prizes redeemed
#{@teacher_bonus_prizes_redeemed}
%br/
%b Teacher bonus prizes available to be redeemed
#{@teacher_bonus_prizes_available}
%br/
%br/

dashboard/app/views/reports/assume_identity_form.html.haml
%h1 Assume identity 

- if flash[:errors]
  #error_explanation
    %h2= flash[:error]

%h2 Be careful! Don't mess up any user data!

= form_tag(assume_identity_url, method: 'POST') do
  Who do you want to be?
  %br/
  = text_field_tag 'user_id', '', :placeholder => 'id, email, or username', :size => 80
  %br/
  = submit_tag 'Go!', :data => {:confirm => 'You really are going to be careful, right?'}

dashboard/app/views/reports/prizes.html.haml
- @page_title = t('redeem_prizes.title', name: current_user.name)

%h1= @page_title

%br/
- if current_user.students.length > 0
  %h4 #{t('home.classroom')}:

  %p
    = link_to t('home.teacher_student_count', count: current_user.students.length), manage_followers_path
    = t('home.teacher_averages', trophy_average: ("%.1f" % current_user.average_student_trophies), trophy_max: Trophy::TROPHY_MAX)
    %br/
    %br/

  - if current_user.teacher_prize.nil? && current_user.teacher_bonus_prize.nil?
    %h4
      %b DonorsChoose.org rewards are no longer available as of June 15, 2014. Please refer to this
      %b= link_to 'FAQ', 'https://support.code.org/hc/en-us/articles/202446516'
      %b for more information.

      %br/
      %br/
  - else
    %h4
      %b
        While DonorsChoose.org rewards are no longer available as of June 15, 2014, you can still use the codes that you have previously claimed (listed below). Be sure to use your codes right away, as they will expire soon! Please refer to this
      %b= link_to 'FAQ', 'https://support.code.org/hc/en-us/articles/202446516'
      %b for more information.

      %br/
      %br/

  - if current_user.teacher_prize
    %h4= t('redeem_prizes.msg.teacher.earned', num_trophies: Trophy::TROPHY_MAX)
    = render partial: 'shared/redeemed_prize', locals: { prize: current_user.teacher_prize }
    %br/

  - if current_user.teacher_bonus_prize
    %h4= t('redeem_prizes.msg.teacher.bonus.earned', num_trophies: Trophy::TROPHY_MAX)
    = render partial: 'shared/redeemed_prize', locals: { prize: current_user.teacher_bonus_prize }
    %br/
- else
  %h4= t('redeem_prizes.no_prizes_available')

%br/
:javascript
  $(document).ready(function() {
    $('a[data-confirm]').click(function(ev) {
      var href = $(this).attr('href');

      if (!$('#dataConfirmModal').length) {
        $('body').append('<div id="dataConfirmModal" tabindex="-1" class="modal" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">#{t('redeem_prizes.confirm.title')}</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">#{t('redeem_prizes.confirm.no')}</button><a class="btn btn-primary" id="dataConfirmOK">#{t('redeem_prizes.confirm.yes')}</a></div></div>');
      }
      $('#dataConfirmModal').find('.modal-body').html($(this).attr('data-confirm'));
      $('#dataConfirmOK').attr('href', href);
      $('#dataConfirmModal').modal({show:true});
      return false;
    });
  });

dashboard/app/views/reports/user_stats.html.haml
%h1 Progress report for #{@user.name}

%h5= t('user_stats.recent_activity')
- @recent_levels.each do |ul|
  = ul.passing? ? t('user_level.completed') : t('user_level.tried')
  #{link_to "#{data_t_suffix('script.name', Script.find(ul.script_id).name, ul.level.game.name)}, #{t('puzzle')} #{ul.game_chapter}", script_level_path(script_id: ul.script_id, id: ul.script_level_id)},
  #{ago(ul.updated_at)}
  %br
=link_to "#{t('user_stats.show_more')}...", usage_path(@user)
%br

= render partial: 'shared/user_stats', locals: { user: @user }

- if current_user && current_user.admin?
  %div{ style: "border: 1px solid red;clear:both"}
    Admin:
    %br
    name: #{@user.name}
    %br
    email: #{@user.email}
    %br
    username: #{@user.username}
    - if @user.age
      %br
      approximmate age: #{@user.age}
    - if @user.gender
      %br
      gender: #{@user.gender}
    %br
    teachers: #{raw @user.teachers.map { |t| link_to(t.name, user_stats_path(t)) }.join(', ')}