dashboard/config/routes.rb
Dashboard::Application.routes.draw do
  resources :gallery_activities, path: '/gallery' do
    collection do
      get 'art', to: 'gallery_activities#index', app: Game::ARTIST
      get 'apps', to: 'gallery_activities#index', app: Game::PLAYLAB
    end
  end
  resources :activity_hints, only: [:update]
  resources :callouts
  resources :videos do
    collection do
      get 'test'
      get 'embed/:key', to: 'videos#embed', as: 'embed'
    end
  end
  resources :concepts
  resources :activities

  resources :sections do
    member do
      post 'log_in'
    end
  end

  resources :level_sources, path: '/sh/', only: [:show, :edit] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end
  get '/share/:id', to: redirect('/sh/%{id}')

  get '/s/k-1(/*all)', to: redirect('/s/course1')
  get '/s/2-3(/*all)', to: redirect('/s/course2')
  get '/s/4-5(/*all)', to: redirect('/s/course3')

  resources :level_source_hints
  get '/add_hint/:level_source_id', :to => 'level_source_hints#add_hint', as: 'add_hint'
  get '/show_hints/:level_source_id', :to => 'level_source_hints#show_hints', as: 'show_hints'
  get '/add_pop_hint/:idx', :to => 'level_source_hints#add_pop_hint', as: 'add_pop_hint'
  get '/show_pop_hints/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints', as: 'show_pop_hints'
  get '/add_pop_hint_per_level/:level_id/:idx', :to => 'level_source_hints#add_pop_hint_per_level', as: 'add_pop_hint_per_level'
  get '/show_pop_hints_per_level/:level_id/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints_per_level', as: 'show_pop_hints_per_level'
  get '/add_hint_access', :to => 'level_source_hints#add_hint_access', as: 'add_hint_access'

  resources :frequent_unsuccessful_level_sources, only: [:index]

  devise_scope :user do
    get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :levels do
    get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
    post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
    post 'clone', to: 'levels#clone'
  end

  resources :games

  get 'builder', to: 'levels#builder'
  post 'upload_maze_level', to: 'levels#upload_maze_level'
  post 'create_custom', to: 'levels#create_custom'
  get 'levels/new', to: 'levels#new'

  resources :scripts, path: '/s/' do
    post 'sort', to: 'scripts#sort'

    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end

    get 'puzzle/:chapter', to: 'script_levels#show', as: 'puzzle', format: false

    resources :stages, only: [:show], path: "/stage", format: false do
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
      end
    end
  end

  get '/beta', to: 'home#beta', as: 'beta'

  get 'reset_session', to: 'application#reset_session_endpoint'

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, reset:true
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false
  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID.to_s, format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID, as: 'editcode_chapter', format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID.to_s, format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID, as: 'twenty_fourteen_chapter', format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID.to_s, format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID, as: 'builder_chapter', format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID.to_s, format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID, as: 'flappy_chapter', format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID.to_s, format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID, as: 'jigsaw_chapter', format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID.to_s, format: false

  resources :followers, only: [:create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'
  get '/followers/sections', to: 'followers#sections', as: 'sections_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove', to: 'followers#remove', as: 'remove_follower'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/level/:level_id', :to => 'activities#milestone', :as => 'milestone_level'
  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/admin/concepts', to: 'reports#admin_concepts', as: 'admin_concepts'
  get '/admin/gallery', to: 'reports#admin_gallery', as: 'admin_gallery'
  get '/admin/assume_identity', to: 'reports#assume_identity_form', as: 'assume_identity_form'
  post '/admin/assume_identity', to: 'reports#assume_identity', as: 'assume_identity'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'
  get '/api/section_progress/:id', to: 'api#section_progress', as: 'section_progress'
  get '/api/student_progress/:section_id/:id', to: 'api#student_progress', as: 'student_progress'
  get '/api/courses', to: 'api#courses', as: 'courses'

  resources :zendesk_session, only: [:index]

  post '/sms/send', to: 'sms#send_to_phone', as: 'send_to_phone'

end

dashboard/app/views/shared/_add_hint.html.haml
=# Local level_source_id and redirect_url must be defined.
= form_for([LevelSourceHint.new]) do |f|
  .field
    = text_area_tag :hint_content, nil, class: 'input-xxlarge',
      placeholder: t('add_hint_form.placeholder'), :required => true,
      :maxlength => 250, :rows => 4
    %br
    %span#content_length_message 250 characters left.
    = hidden_field_tag :level_source_id, level_source_id
    = hidden_field_tag :redirect, redirect_url
  .actions
    = f.submit t('add_hint_form.submit')

:javascript
  $( "#hint_content" ).placeholder();

  $( "#hint_content" ).on('input',function(e){
    var remain_char_num = 250 - $( '#hint_content' ).val().length;
    $( '#content_length_message' ).text(remain_char_num + " characters left.");
  });

dashboard/app/views/shared/_ajax_submit.js.erb
$(document).ready(function () {
  var form_selector = '<%=form_selector%>';
  console.log('form selector=' + form_selector);
  $(form_selector).on('ajax:beforeSend', function (e, xhr) {
    $('#validation-error').empty();
    var token = $('meta[name="csrf-token"]').attr('content');
    xhr.setRequestHeader('X-CSRF-TOKEN', token);
  });
  $(form_selector).on('ajax:complete', function (e, data) {
    if (data.status == "200") {
      window.location.href = JSON.parse(data.responseText).redirect
    }
  });
  $(form_selector).on("ajax:error", function (evt, xhr, status, error) {
    var errors, errorText;
    try {
      errors = $.parseJSON(xhr.responseText);
    } catch (err) {
      errors = {message: "Error (" + error + "): " + xhr.responseText};
    }
    $('#validation-error')
      .html("<p>Couldn't create level:</p>")
      .append($("<ul/>")
        .append(Object.keys(errors).map(function (v) {
          return $("<li/>").text(v + ": " + errors[v]);
        })));
  });
});

dashboard/app/views/shared/_concept_trophy_block.html.haml
%div{style:"display:inline-block;width:290px;position:relative;overflow:hidden;" + added_style}
  %h4 #{t('nav.popup.mastery')}

  %table{style:"max-width:290px;"}
    - if concept_progress
      - concept_progress.each_pair do |concept, counts|
      - completion = counts[:current].to_f/counts[:max]
        =render partial: 'shared/concept_trophy_row', locals: { concept: concept, completion: completion }
        <!-- #{counts} -->
    - else
      - Concept.cached.each do |concept|
        =render partial: 'shared/concept_trophy_row', locals: { concept: concept, completion: 0 }

dashboard/app/views/shared/_concept_trophy_row.html.haml
%tr{ height:"55px"}
  %td{width:"100px"}
    #{data_t('concept.description', concept.name)}:
  %td{width:"55px", style:"text-align:center;"}
    = image_tag image_url(bronze_fraction_image_path(completion)), class: "trophy_image"
  %td{width:"55px", style:"text-align:center;"}
    = image_tag image_url(silver_fraction_image_path(completion)), class: "trophy_image"
  %td{width:"55px", style:"text-align:center;"}
    = image_tag image_url(gold_fraction_image_path(completion)), class: "trophy_image"

dashboard/app/views/shared/_course_tall_block.haml
- if id == "hoc"
  - url = hoc_reset_url()
  - title = t('upsell.hoc.title')
  - body = t('upsell.hoc.body')

- elsif id == "flappy"
  - url = url_from_path("/flappy/1")
  - title = t('upsell.flappy.title')
  - body = t('upsell.flappy.body')

- elsif id == "20hour"
  - url = script_url(id)
  - title = t('upsell.20hour.title')
  - body = t('upsell.20hour.body')

- elsif id == "course1" || id == "course2" || id == "course3" || id == "artist" || id == "playlab"
  - url = script_url(id)
  - title = data_t_suffix('script.name', id, "title")
  - body = data_t_suffix('script.name', id, "description_short")

- if id == "artist" || id == "playlab"
  - url = script_stage_script_level_url(id, 1, 1)
  - title = data_t_suffix('script.name', id, "title")
  - body = data_t_suffix('script.name', id, "description_short")

.span3.miniblock.miniblock-tall{style: "overflow:hidden"}
  =link_to url, {style:"text-decoration:none"} do
    .heading{style: "padding-left: 10px; padding-right: 10px; padding-top: 0px; padding-bottom: 5px; "}
      %h3.whitetext{style: "text-overflow: ellipsis; white-space: nowrap; overflow: hidden"}
        = title

    .imgspan
      = image_tag(image_url("logo_tall_#{id}.jpg"), height: "120", style: "width: 100%; height: 120px")
    %br/
    %br/

    .clear

    .smalltext.greytext{style: "padding-left: 10px; padding-right: 10px; padding-top: 10px; "}= body

dashboard/app/views/shared/_course_wide_block.haml
-if id == "hoc"
  .span6.miniblock
    =link_to hoc_reset_url() do
      .span4.heading
        %h3.whitetext= t('upsell.hoc.title')
        .smalltext.whitetext= t('upsell.hoc.body')
      .span2.imgspan{style: "margin-left: 0px"}
        %img{style: "height: 100px", src: "//code.org/images/fit-520/codehoc3.jpg"}

-elsif id == "flappy"
  .span6.miniblock
    =link_to url_from_path("/flappy/1") do
      .span4.heading
        %h3.whitetext= t('upsell.flappy.title')
        .smalltext.whitetext= t('upsell.flappy.body')
      .span1.imgspan{style: "margin-left: 0px"}
        %img{style: "padding-left: 42px; padding-top: 20px;", src: "//studio.code.org/blockly/media/skins/flappy/small_static_avatar.png"}

-elsif id == "20hour"
  .span6.miniblock
    =link_to script_url(1) do
      .span4.heading
        %h3.whitetext= t('upsell.20hour.title')
        .smalltext.whitetext= t('upsell.20hour.body')
      .span2.imgspan
        %img{style: "height: 100px", src: "//code.org/images/fit-520/code20hr.jpg"}

-elsif id == "course1" || id == "course2" || id == "course3"
  .span9.miniblock.miniblock-short
    =link_to script_url(id) do
      .span7.heading
        %h3.whitetext
          = data_t_suffix('script.name', id, "title")
        .smalltext.whitetext= data_t_suffix('script.name', id, "description")
      .span2.imgspan
        %br/
        = image_tag(image_url("logo_#{id}.jpg"), height: 100)

dashboard/app/views/shared/_edit_hint_table_status_button.html.haml
-# This should be rendered from _edit_hint_table.html.haml (where update_status
-# is defined) with local status_val and level_source_hint, and it assumes that
-# the user is an administrator.  (Otherwise, the user shouldn't be given the
-# option of changing the status.
= radio_button_tag 'status', status_val, level_source_hint.status == status_val,
  :onchange => "updateHint(\'#{level_source_hint_path(level_source_hint.id)}\', {'status' : \'#{status_val}\'});"

dashboard/app/views/shared/_redeemed_prize.html.haml
- provider = prize.prize_provider
= image_tag provider.image_name, :class => 'prize-card-img'
%p
  %b= t('redeem_prizes.provider')
  = link_to(t('redeem_prizes.providers.' + provider.description_token), provider.url)
%p
  %b= t('redeem_prizes.code')
  %span{class: 'prize-code'} #{prize.code}
%p
  %span{class: 'prize-redemption'} #{Dashboard::Application::config.prize_providers[provider.description_token]['redemption']}
- if prize.class == TeacherPrize || prize.class == TeacherBonusPrize
  = link_to t('redeem_prizes.donorschoose_register'), 'http://www.donorschoose.org/teachers', target: "_blank"
  %br/
  = link_to t('redeem_prizes.donorschoose_project'), 'http://www.donorschoose.org/docs/Teacher%20Registration%20Packet%206.11.14%20(1).pdf', target: "_blank"
  %br/
  = link_to t('redeem_prizes.donorschoose_how_to'), 'http://www.donorschoose.org/docs/how-to-use-gift-code-2.pdf', target: "_blank"

dashboard/app/views/shared/_student_continue.html.haml
#last
  - script_level = current_user.next_unpassed_progression_level(script)
  - if script_level
    #left_off #{t('home.student_left_off')}
    - stage_or_game = script_level.stage ? script_level.stage : script_level.level.game
    %em= data_t_suffix('script.name', script.name, stage_or_game.name)
    #{t('puzzle')} #{script_level.game_chapter}
    &nbsp;
    = form_tag(build_script_level_url(script_level), method: 'get', style: "display:inline;") do
      = submit_tag t('continue'), name: nil, class: 'btn btn-primary button-continue', id: 'continue_button'
  - elsif include_finished
    = render partial: 'shared/student_finished'

dashboard/app/views/shared/_student_finished.html.haml
= raw t('home.student_finished', online_link: link_to(t('home.online'), 'http://code.org/learn/beyond'), local_school_link: link_to(t('home.local_school'), 'http://code.org/learn/local'))

dashboard/app/views/shared/_teacher_nav.html.haml
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'manage', t('teacher.students.manage'), manage_followers_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'sections', t('teacher.sections.manage'), sections_followers_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'report', t('teacher.rollup'), followers_path
|
%span{ style: 'color: #ffa400;'}
  = link_to_if current != 'activity', t('teacher.activity'), student_usage_path

dashboard/app/views/shared/_user_header.html.haml
- if current_user
  .transparent_backdrop{style: 'display:none;'}
  .user_menu
    = link_to raw("#{t('nav.user.label', username: h(current_user.short_name))} &#x25BC;"), '#', onclick: "return handleUserMenuClick();", class: 'user-menu-link'
    %div{ style: 'position:relative;top:3px;'}
      .user_options{style: 'display: none;'}
        - if current_user.teacher?
          = link_to t('nav.user.classroom'), teacher_dashboard_url
          %hr
        = link_to t('nav.user.stats'), root_url
        %br/
        = link_to t('nav.user.settings'), edit_user_registration_url
        %br/
        - if current_user.teacher? && (current_user.teacher_prize || current_user.teacher_bonus_prize)
          = link_to t('nav.user.prizes'), my_prizes_url
          %br/
        = link_to t('nav.user.logout'), destroy_user_session_url
- elsif params[:controller] !~ /^devise/ and not Rails.configuration.minimal_mode

  = link_to(t('nav.user.signin'), new_user_session_url, class: 'button-signin', id: 'signin_button')

dashboard/app/views/shared/_user_stats.html.haml
- script = @script || (user && user.primary_script) || Script.twenty_hour_script
- script_levels = user ? user.levels_from_script(script) : script.script_levels.includes(:script, :stage, level: :game)
- concept_progress = user ? user.concept_progress : nil

.user-stats-block
  - levels = script_levels.group_by(&:stage_or_game)
  - levels.each_pair do |stage_or_game, sl_group|
    - should_show_lesson_plan = script.has_lesson_plan? && current_user && current_user.teacher?
    .game-group
      .stage
        %span
          = stage_title(script, stage_or_game)
        - if should_show_lesson_plan
          .stage-lesson-plan-link
            = link_to t('view_lesson_plan'), lesson_plan_html_url(stage_or_game)

      .games
        - sl_group = sl_group.sort_by {|sl| sl.stage_or_game_position}
        - sl_group.each do |sl|
          .level
            - css_class, link = level_info(user, sl)
            - if params[:script_level_id] && params[:script_level_id] == sl.level_id.to_s
              - puzzle_outer_class = 'puzzle_outer_current'
            - elsif sl.assessment
              - puzzle_outer_class = 'puzzle_outer_assessment'
            - else
              - puzzle_outer_class = 'puzzle_outer_level'
            %span{class: puzzle_outer_class}
              %a.level_link{ href: link, class: css_class}
                - unplugged = sl.level.unplugged?
                - if unplugged
                  %span.puzzle-named
                    =sl.level_display_text
                - elsif css_class == 'passed'
                  = check_mark_html
                - elsif css_class == 'perfect'
                  = check_mark_html
                - else 
                  %span.puzzle-number
                    =sl.level_display_text
  = render partial: 'shared/user_stats_key'
-if script.trophies?
  %div{style:"clear:both"}
  #trophies
    =render partial: 'shared/concept_trophy_block', locals: { concept_progress: concept_progress, user: user, added_style: 'padding:10px;' }

dashboard/app/views/shared/overloaded.html.haml
%h1 Oh no!

%h2
  Too many people are trying to learn to code all at once and our poor little
  servers can't handle it.

%h3
  We've temporarily disabled our accounts system and some other functionality
  so that we can better serve all of our visitors.

%center
  %br
  %big
    = link_to 'Go to the homepage', root_url
    or
    = link_to 'Visit one of our partners', 'http://code.org/learn/'
  %br
  %br
  %br