dashboard/config/routes.rb
Dashboard::Application.routes.draw do
  resources :gallery_activities, path: '/gallery' do
    collection do
      get 'art', to: 'gallery_activities#index', app: Game::ARTIST
      get 'apps', to: 'gallery_activities#index', app: Game::PLAYLAB
    end
  end
  resources :activity_hints, only: [:update]
  resources :callouts
  resources :videos do
    collection do
      get 'test'
      get 'embed/:key', to: 'videos#embed', as: 'embed'
    end
  end
  resources :concepts
  resources :activities

  resources :sections do
    member do
      post 'log_in'
    end
  end

  resources :level_sources, path: '/sh/', only: [:show, :edit] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end
  get '/share/:id', to: redirect('/sh/%{id}')

  get '/s/k-1(/*all)', to: redirect('/s/course1')
  get '/s/2-3(/*all)', to: redirect('/s/course2')
  get '/s/4-5(/*all)', to: redirect('/s/course3')

  resources :level_source_hints
  get '/add_hint/:level_source_id', :to => 'level_source_hints#add_hint', as: 'add_hint'
  get '/show_hints/:level_source_id', :to => 'level_source_hints#show_hints', as: 'show_hints'
  get '/add_pop_hint/:idx', :to => 'level_source_hints#add_pop_hint', as: 'add_pop_hint'
  get '/show_pop_hints/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints', as: 'show_pop_hints'
  get '/add_pop_hint_per_level/:level_id/:idx', :to => 'level_source_hints#add_pop_hint_per_level', as: 'add_pop_hint_per_level'
  get '/show_pop_hints_per_level/:level_id/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints_per_level', as: 'show_pop_hints_per_level'
  get '/add_hint_access', :to => 'level_source_hints#add_hint_access', as: 'add_hint_access'

  resources :frequent_unsuccessful_level_sources, only: [:index]

  devise_scope :user do
    get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :levels do
    get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
    post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
    post 'clone', to: 'levels#clone'
  end

  resources :games

  get 'builder', to: 'levels#builder'
  post 'upload_maze_level', to: 'levels#upload_maze_level'
  post 'create_custom', to: 'levels#create_custom'
  get 'levels/new', to: 'levels#new'

  resources :scripts, path: '/s/' do
    post 'sort', to: 'scripts#sort'

    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end

    get 'puzzle/:chapter', to: 'script_levels#show', as: 'puzzle', format: false

    resources :stages, only: [:show], path: "/stage", format: false do
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
      end
    end
  end

  get '/beta', to: 'home#beta', as: 'beta'

  get 'reset_session', to: 'application#reset_session_endpoint'

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, reset:true
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false
  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID.to_s, format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID, as: 'editcode_chapter', format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID.to_s, format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID, as: 'twenty_fourteen_chapter', format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID.to_s, format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID, as: 'builder_chapter', format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID.to_s, format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID, as: 'flappy_chapter', format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID.to_s, format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID, as: 'jigsaw_chapter', format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID.to_s, format: false

  resources :followers, only: [:create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'
  get '/followers/sections', to: 'followers#sections', as: 'sections_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove', to: 'followers#remove', as: 'remove_follower'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/level/:level_id', :to => 'activities#milestone', :as => 'milestone_level'
  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/admin/concepts', to: 'reports#admin_concepts', as: 'admin_concepts'
  get '/admin/gallery', to: 'reports#admin_gallery', as: 'admin_gallery'
  get '/admin/assume_identity', to: 'reports#assume_identity_form', as: 'assume_identity_form'
  post '/admin/assume_identity', to: 'reports#assume_identity', as: 'assume_identity'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'
  get '/api/section_progress/:id', to: 'api#section_progress', as: 'section_progress'
  get '/api/student_progress/:section_id/:id', to: 'api#student_progress', as: 'student_progress'
  get '/api/courses', to: 'api#courses', as: 'courses'

  resources :zendesk_session, only: [:index]

  post '/sms/send', to: 'sms#send_to_phone', as: 'send_to_phone'

end

dashboard/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_locale
    set_locale_cookie(params[:locale]) if params[:locale]
    redirect_to params[:return_to].to_s
  end

  def check_username
    if !params[:username] || params[:username].length < 5
      render json: { message: I18n.t('signup_form.invalid_username'), available: false }
    else
      if User.exists?(username: params[:username])
        render json: { message: I18n.t('signup_form.taken_username'), available: false }
      else
        render json: { message: I18n.t('signup_form.valid_username'), available: true }
      end
    end
  end

  def home_insert
    if current_user
      render 'index', layout: false, formats: [:html]
    else
      render text: ''
    end
  end

  def health_check
    render text: 'healthy!'
  end
end

dashboard/app/helpers/home_helper.rb
module HomeHelper
end

dashboard/app/views/home/_admin.html.haml
- if current_user && current_user.admin?
  %h3= t(:demos)
  = link_to "Games", games_path
  |
  = link_to "Concepts", concepts_path
  |
  = link_to "Videos", videos_path
  |
  = link_to "Recent Activity", all_usage_path
  %br/
  %br/
  %ul
    %li= link_to 'Feedback System', frequent_unsuccessful_level_sources_path
    %li
      = link_to('Scripts', scripts_path)
      = link_to('(Update all)', scripts_path(rake: '1'))
      %ul
        - Script.all.each do |script|
          %li
            = link_to("(#{t 'crud.edit'})", edit_script_path(script)) unless script.default_script?
            = link_to(data_t_suffix('script.name', script.name, 'title'), script_level_path(script, ScriptLevel::NEXT))
  = link_to t("builder.manage"), levels_new_path
  %h3= link_to 'Admin Stats', admin_stats_path
  %h3= link_to 'Gallery', admin_gallery_path
  %br/
  %br/

dashboard/app/views/home/_gallery.html.haml
- [Game::STUDIO, Game::ARTIST].each do |app|
  - unless current_user.gallery_activities.where(app: app).empty?
    %h4= t("home.gallery.your_#{app}")
    %div.gallery{id: "#{app}-gallery"}
      - current_user.gallery_activities.where(app: app).limit(5).each do |gallery_activity|
        - level_source = gallery_activity.try(:activity).try(:level_source)
        - if level_source
          %div.gallery_activity
            = link_to(image_tag(original_image_level_source_path(level_source)), level_source)
    .clear

dashboard/app/views/home/beta.html.haml
.row
  .span9
    %h1 Beta courses
    These courses are in <b>beta</b>. This means they are not the final versions of the courses, and are subject to revision as feedback is received and improvements are made.
.row
  .span12
    &nbsp;
.row
  .span12
    = render partial: 'shared/course_wide_block', locals: { id: "course1" }
.row
  .span12
    &nbsp;
.row
  .span12
    = render partial: 'shared/course_wide_block', locals: { id: "course2" }
.row
  .span12
    &nbsp;
.row
  .span12
    = render partial: 'shared/course_wide_block', locals: { id: "course3" }

%br/
%br/
%br/

dashboard/app/views/home/debug.html.haml
%h1 Debug page

%table{ border: "1" }
  %tr
    %td Params
    %td= params.inspect
  %tr
    %th Cookies
  - cookies.each do |c|
    %tr
      %td= c[0]
      %td= c[1]
  %tr
    %th Request Env
  - request.env.each_pair do |k,v|
    %tr
      %td= k
      %td= v
  %tr
    %td Request
    %td= request.inspect

dashboard/app/views/home/index.html.haml
#landingpage
  - flash.delete(:notice)
  %h1= t('home.title')
  - if current_user
    .row
      .span10
        %h2= t('welcome_back', name: current_user.name)

      .span2
        - if current_user.students.length > 0 || current_user.teacher?
          %br/
          = button_to t('home.use_as_teacher'), teacher_dashboard_url, :class=>"btn btn-info biggerbutton"

    .row
      .span12
        - if current_user.primary_script
          %h4 #{t('home.student_progress')}:
          - if current_user.primary_script.trophies?
            = t('home.student_stats', trophy_count: current_user.trophy_count, trophy_max: Trophy::TROPHY_MAX)
            %br/

          %div.padtopbottom
            = render partial: 'shared/student_continue', locals: { include_finished: true, script: current_user.primary_script }
            - if !current_user.teacher? && current_user.teachers.length == 0
              = link_to t('add_teacher_form.submit'), "#section_code"
        - unless current_user.gallery_activities.empty?
          = render partial: 'home/gallery'
    %br/

    - if current_user && current_user.primary_script
      = render partial: 'shared/course_progress_block', locals: { script: current_user.primary_script }
  - else
    - unless Rails.configuration.minimal_mode

      .row#signup
        .span6
          %a{style: "text-decoration:none", href: new_user_registration_path}
            %button.btn= t('home.student_reg_link')

          %a{href: new_user_registration_path('user[user_type]' => User::TYPE_TEACHER)}
            %button.btn= t('home.teacher_reg_link')

        .span6{style: "text-align:right"}
          %div{style: "float:right"}
            %a{href: new_user_session_path}
              %button.btn= t('nav.user.signin')
          %div{style: "float:right"}
            .registertext= t('nav.user.already_registered')

      %br/

    .row
      = render partial: '/shared/course_big_block', locals: {id: "hoc" }
    %br/
    .row
      .span12.twolineheader!= t('home.heading_elementary')
      = render partial: 'shared/course_tall_block', locals: { id: "course1" }
      = render partial: 'shared/course_tall_block', locals: { id: "course2" }
      = render partial: 'shared/course_tall_block', locals: { id: "course3" }
    %br/
    .row
      .span12.twolineheader!= t('home.heading_apps')
    .row
      = render partial: 'shared/course_tall_block', locals: { id: "playlab" }
      = render partial: 'shared/course_tall_block', locals: { id: "flappy" }
      = render partial: 'shared/course_tall_block', locals: { id: "artist" }
    %br/
    .row
      .span12.twolineheader!= t('home.heading_legacy')
    .row
      = render partial: 'shared/course_wide_block', locals: { id: "20hour" }

  %br/
  - if current_user && !current_user.teacher?
    - if current_user.teachers.length >= 1
      = t('teacher.title', count: current_user.teachers.length, name: '')
      = raw current_user.teachers.map{|t| t[:name] + ' ' + link_to(t('teacher.remove'), remove_follower_path(teacher_user_id: t[:id], student_user_id: current_user.id), confirm: t('teacher.confirm.remove'), method: :post)}.join(', ')
    - else
      %h4= t('add_teacher_form.code.label')
      = form_for([Follower.new]) do |f|
        .field
          = text_field_tag :section_code, nil, class: 'input-xxlarge', placeholder: t('add_teacher_form.code.placeholder'), :required => true
          = hidden_field_tag :redirect, root_path
        .actions
          = f.submit t('add_teacher_form.submit')
    %br/
    %br/
  %br/

  - if current_user && current_user.admin?
    = render partial: 'home/admin'

  - if current_user
    .row
      .span12.twolineheader!= t('home.heading_elementary')
      = render partial: 'shared/course_tall_block', locals: { id: "course1" }
      = render partial: 'shared/course_tall_block', locals: { id: "course2" }
      = render partial: 'shared/course_tall_block', locals: { id: "course3" }
    %br/
    .row
      .span12.twolineheader!= t('home.heading_apps')
    .row
      = render partial: 'shared/course_tall_block', locals: { id: "playlab" }
      = render partial: 'shared/course_tall_block', locals: { id: "flappy" }
      = render partial: 'shared/course_tall_block', locals: { id: "artist" }
      = render partial: 'shared/course_tall_block', locals: { id: "hoc" }
    %br/
    .row
      .span12.twolineheader!= t('home.heading_legacy')
    .row
      = render partial: 'shared/course_wide_block', locals: { id: "20hour" }


  %br/
  %br/
  %br/

  :javascript
    $( "#section_code" ).placeholder();