dashboard/config/routes.rb
Dashboard::Application.routes.draw do
  resources :gallery_activities, path: '/gallery' do
    collection do
      get 'art', to: 'gallery_activities#index', app: Game::ARTIST
      get 'apps', to: 'gallery_activities#index', app: Game::PLAYLAB
    end
  end
  resources :activity_hints, only: [:update]
  resources :callouts
  resources :videos do
    collection do
      get 'test'
      get 'embed/:key', to: 'videos#embed', as: 'embed'
    end
  end
  resources :concepts
  resources :activities

  resources :sections do
    member do
      post 'log_in'
    end
  end

  resources :level_sources, path: '/sh/', only: [:show, :edit] do
    member do
      get 'generate_image'
      get 'original_image'
    end
  end
  get '/share/:id', to: redirect('/sh/%{id}')

  get '/s/k-1(/*all)', to: redirect('/s/course1')
  get '/s/2-3(/*all)', to: redirect('/s/course2')
  get '/s/4-5(/*all)', to: redirect('/s/course3')

  resources :level_source_hints
  get '/add_hint/:level_source_id', :to => 'level_source_hints#add_hint', as: 'add_hint'
  get '/show_hints/:level_source_id', :to => 'level_source_hints#show_hints', as: 'show_hints'
  get '/add_pop_hint/:idx', :to => 'level_source_hints#add_pop_hint', as: 'add_pop_hint'
  get '/show_pop_hints/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints', as: 'show_pop_hints'
  get '/add_pop_hint_per_level/:level_id/:idx', :to => 'level_source_hints#add_pop_hint_per_level', as: 'add_pop_hint_per_level'
  get '/show_pop_hints_per_level/:level_id/:idx(/:restriction)', :to => 'level_source_hints#show_pop_hints_per_level', as: 'show_pop_hints_per_level'
  get '/add_hint_access', :to => 'level_source_hints#add_hint_access', as: 'add_hint_access'

  resources :frequent_unsuccessful_level_sources, only: [:index]

  devise_scope :user do
    get '/oauth_sign_out/:provider', to: 'sessions#oauth_sign_out', as: :oauth_sign_out
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions'
  }

  post '/signup_check/username', to: 'home#check_username'

  root :to => "home#index"
  get '/home_insert', to: 'home#home_insert'
  get '/health_check', to: 'home#health_check'
  get '/admin/debug', to: 'home#debug'

  post '/locale', to: 'home#set_locale', as: 'locale'

  resources :levels do
    get 'edit_blocks/:type', to: 'levels#edit_blocks', as: 'edit_blocks'
    post 'update_blocks/:type', to: 'levels#update_blocks', as: 'update_blocks'
    post 'clone', to: 'levels#clone'
  end

  resources :games

  get 'builder', to: 'levels#builder'
  post 'upload_maze_level', to: 'levels#upload_maze_level'
  post 'create_custom', to: 'levels#create_custom'
  get 'levels/new', to: 'levels#new'

  resources :scripts, path: '/s/' do
    post 'sort', to: 'scripts#sort'

    resources :script_levels, as: :levels, only: [:show], path: "/level", format: false do
      get 'solution', to: 'script_levels#solution'
    end

    get 'puzzle/:chapter', to: 'script_levels#show', as: 'puzzle', format: false

    resources :stages, only: [:show], path: "/stage", format: false do
      resources :script_levels, only: [:show], path: "/puzzle", format: false do
      end
    end
  end

  get '/beta', to: 'home#beta', as: 'beta'

  get 'reset_session', to: 'application#reset_session_endpoint'

  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID, reset:true, as: 'hoc_reset'
  get '/hoc/reset', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, reset:true
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID, as: 'hoc_chapter', format: false
  get '/hoc/:chapter', to: 'script_levels#show', script_id: Script::HOC_ID.to_s, format: false

  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID, as: 'k8intro_chapter', format: false
  get '/k8intro/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_HOUR_ID.to_s, format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID, as: 'editcode_chapter', format: false
  get '/editcode/:chapter', to: 'script_levels#show', script_id: Script::EDIT_CODE_ID.to_s, format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID, as: 'twenty_fourteen_chapter', format: false
  get '/2014/:chapter', to: 'script_levels#show', script_id: Script::TWENTY_FOURTEEN_LEVELS_ID.to_s, format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID, as: 'builder_chapter', format: false
  get '/builder/:chapter', to: 'script_levels#show', script_id: Script::BUILDER_ID.to_s, format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID, as: 'flappy_chapter', format: false
  get '/flappy/:chapter', to: 'script_levels#show', script_id: Script::FLAPPY_ID.to_s, format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID, as: 'jigsaw_chapter', format: false
  get '/jigsaw/:chapter', to: 'script_levels#show', script_id: Script::JIGSAW_ID.to_s, format: false

  resources :followers, only: [:create, :index]
  get '/followers/:teacher_user_id/accept', to: 'followers#accept', as: 'follower_accept'
  post '/followers/create_student', to: 'followers#create_student', as: 'create_student'
  get '/followers/manage', to: 'followers#manage', as: 'manage_followers'
  get '/followers/sections', to: 'followers#sections', as: 'sections_followers'

  get '/followers/change_password/:user_id', to: 'followers#student_edit_password', as: 'student_edit_password'
  post '/followers/save_password', to: 'followers#student_update_password', as: 'student_update_password'

  post '/followers/add_to_section', to: 'followers#add_to_section', as: 'add_to_section'
  post '/followers/remove', to: 'followers#remove', as: 'remove_follower'
  get '/join(/:section_code)', to: 'followers#student_user_new', as: 'student_user_new'
  post '/join/:section_code', to: 'followers#student_register', as: 'student_register'

  post '/milestone/:user_id/level/:level_id', :to => 'activities#milestone', :as => 'milestone_level'
  post '/milestone/:user_id/:script_level_id', :to => 'activities#milestone', :as => 'milestone'

  get '/admin/usage', to: 'reports#all_usage', as: 'all_usage'
  get '/admin/stats', to: 'reports#admin_stats', as: 'admin_stats'
  get '/admin/progress', to: 'reports#admin_progress', as: 'admin_progress'
  get '/admin/concepts', to: 'reports#admin_concepts', as: 'admin_concepts'
  get '/admin/gallery', to: 'reports#admin_gallery', as: 'admin_gallery'
  get '/admin/assume_identity', to: 'reports#assume_identity_form', as: 'assume_identity_form'
  post '/admin/assume_identity', to: 'reports#assume_identity', as: 'assume_identity'
  get '/stats/usage/:user_id', to: 'reports#usage', as: 'usage'
  get '/stats/students', to: 'reports#students', as: 'student_usage'
  get '/stats/:user_id', to: 'reports#user_stats', as: 'user_stats'
  get '/stats/level/:level_id', to: 'reports#level_stats', as: 'level_stats'
  get '/popup/stats', to: 'reports#header_stats', as: 'header_stats'
  get '/redeemprizes', to: 'reports#prizes', as: 'my_prizes'

  get '/notes/:key', to: 'notes#index'

  get '/api/user_menu', to: 'api#user_menu', as: 'user_menu'
  get '/api/user_hero', to: 'api#user_hero', as: 'user_hero'
  get '/api/section_progress/:id', to: 'api#section_progress', as: 'section_progress'
  get '/api/student_progress/:section_id/:id', to: 'api#student_progress', as: 'student_progress'
  get '/api/courses', to: 'api#courses', as: 'courses'

  resources :zendesk_session, only: [:index]

  post '/sms/send', to: 'sms#send_to_phone', as: 'send_to_phone'

end

dashboard/app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :game
  has_and_belongs_to_many :concepts
  has_many :script_levels, dependent: :destroy
  belongs_to :solution_level_source, :class_name => "LevelSource" # TODO do we even use this
  belongs_to :ideal_level_source, :class_name => "LevelSource" # "see the solution" link uses this
  belongs_to :user
  has_many :level_sources

  validates_length_of :name, within: 1..70
  validates_uniqueness_of :name, case_sensitive: false, conditions: -> { where.not(user_id: nil) }

  after_save :write_custom_level_file
  after_destroy :delete_custom_level_file

  include StiFactory
  include SerializedProperties

  serialized_attrs %w(video_key)

  # Fix STI routing http://stackoverflow.com/a/9463495
  def self.model_name
    self < Level ? Level.model_name : super
  end

  # https://github.com/rails/rails/issues/3508#issuecomment-29858772
  # Include type in serialization.
  def serializable_hash(options=nil)
    super.merge 'type' => type
  end

  def related_videos
    ([game.intro_video, specified_autoplay_video] + concepts.map(&:video)).reject(&:nil?).uniq
  end

  def specified_autoplay_video
    Video.find_by_key(video_key)
  end

  def complete_toolbox(type)
    "<xml id='toolbox' style='display: none;'>#{toolbox(type)}</xml>"
  end

  # Overriden by different level types.
  def toolbox(type)
  end

  def unplugged?
    game && game.unplugged?
  end

  # Overriden by different level types.
  def self.start_directions
  end

  # Overriden by different level types.
  def self.step_modes
  end

  # Overriden by different level types.
  def self.flower_types
  end

  def self.custom_levels
    Naturally.sort_by(Level.where.not(user_id: nil), :name)
  end

  def custom?
    user_id.present?
  end

  def self.load_custom_levels
    Dir.glob(Rails.root.join('config/scripts/**/*.level')).sort.map do |path|
      load_custom_level(File.basename(path, File.extname(path)))
    end
  end

  def self.level_file_path(name)
    level_paths = Dir.glob(Rails.root.join("config/scripts/**/#{name}.level"))
    raise("Multiple .level files for '#{name}' found: #{level_paths}") if level_paths.many?
    level_paths.first
  end

  def self.load_custom_level(name)
    level_path = level_file_path(name) || raise("Level #{name} not found")
    load_custom_level_xml(File.read(level_path), name)
  end

  def self.load_custom_level_xml(xml, name)
    level_xml = Nokogiri::XML(xml)
    type = level_xml.root.name
    transaction do
      level = Level.find_or_create_by(name: name).with_type(type)
      level.load_level_xml(xml)
    end
  end

  def load_level_xml(xml)
    json = Nokogiri::XML(xml, &:noblanks).xpath('//../config').first.text
    level_hash = JSON.parse(json)
    update!(level_hash)
    self
  end

  def self.write_custom_levels
    level_paths = Dir.glob(Rails.root.join('config/scripts/**/*.level'))
    written_level_paths = Level.custom_levels.map(&:write_custom_level_file)
    (level_paths - written_level_paths).each { |path| File.delete path }
  end

  def write_custom_level_file
    if write_to_file?
      file_path = self.class.level_file_path(name) || Rails.root.join("config/scripts/levels/#{name}.level")
      File.write(file_path, self.to_xml)
      file_path
    end
  end

  def to_xml(options={})
    builder = Nokogiri::XML::Builder.new do |xml|
      xml.send(self.type) do
        xml.config do
          config_attributes = filter_level_attributes(self.serializable_hash.deep_dup)
          xml.cdata(JSON.pretty_generate(config_attributes.as_json))
        end
      end
    end
    builder.to_xml(PRETTY_PRINT)
  end

  PRETTY_PRINT = {save_with: Nokogiri::XML::Node::SaveOptions::NO_DECLARATION | Nokogiri::XML::Node::SaveOptions::FORMAT}

  def self.pretty_print(xml_string)
    xml = Nokogiri::XML(xml_string, &:noblanks)
    xml.serialize(PRETTY_PRINT).strip
  end

  def filter_level_attributes(level_hash)
    %w(name id updated_at type ideal_level_source_id).each {|field| level_hash.delete field }
    level_hash.reject! { |k, v| v.nil? }
    level_hash
  end

  def delete_custom_level_file
    if write_to_file?
      file_path = Dir.glob(Rails.root.join("config/scripts/**/#{name}.level")).first
      File.delete(file_path) if file_path && File.exists?(file_path)
    end
  end

  def self.update_unplugged
    # Unplugged level data is specified in 'unplugged.en.yml' file
    unplugged = I18n.t('data.unplugged')
    unplugged_game = Game.find_by(name: 'Unplugged')
    unplugged.map do |name,_|
      Level.where(name: name).first_or_create.update(
        type: 'Unplugged',
        game: unplugged_game
      )
    end
  end

  def calculate_ideal_level_source_id
    ideal_level_source =
      level_sources.
      includes(:activities).
      max_by {|level_source| level_source.activities.where("test_result >= #{Activity::FREE_PLAY_RESULT}").count}

    self.update_attribute(:ideal_level_source_id, ideal_level_source.id) if ideal_level_source
  end

  private

  def write_to_file?
    custom? && Rails.env.levelbuilder? && !ENV['FORCE_CUSTOM_LEVELS']
  end
end

dashboard/app/views/levels/_admin.html.haml
- if current_user.try(:admin?)
  :scss
    .admin {
      border: 2px solid #888;
      padding: 10px;
      background: #ccc;
      position: fixed;
      bottom: 0;
      right: 0;
      h4 {
        font-size: 14px;
        font-weight: bold;
        margin: 0 0 5px 0;
      }
    }
  .admin
    %h4
      Admins:
      %a{href: '#', onclick: '$(".admin .content").toggle(); return false;'} [hide/show]
    .content
      #{@level.name}:
      = link_to "play", @level
      - if can? :edit, @level
        \/
        = link_to "edit", edit_level_path(@level)
        (
        - if @level.is_a? Artist or @level.is_a? Calc
          = link_to "solution", level_edit_blocks_path(@level, :solution_blocks)
          \/
        = link_to "toolbox", level_edit_blocks_path(@level, :toolbox_blocks)
        \/
        = link_to "start", level_edit_blocks_path(@level, :start_blocks)
        \/
        = link_to "required", level_edit_blocks_path(@level, :required_blocks)
        \/
        = link_to "pre-draw", level_edit_blocks_path(@level, :predraw_blocks)
        )
      - else
        \/
        (Cannot edit)
      \/
      = link_to "stats", level_stats_path(@level)

      %br/
      This level is in the following scripts:
      %ul
        - @level.script_levels.each do |script_level|
          %li
            = link_to script_level.script.name, script_level.script
            as
            = link_to build_script_level_path(script_level), build_script_level_path(script_level)

dashboard/app/views/levels/_blockly.html.haml
#blocklyApp
  .loading
  .slow_load
    = t(:slow_loading)
    %br
    %a{href: 'javascript: location.reload();'}= t(:try_reloading)

- content_for :body_scripts do
  -# Common scripts and styles
  - blockly_path = "#{ActionController::Base.asset_host}/blockly/"
  -# If no param, take default
  - pretty = params.fetch(:pretty, Rails.configuration.pretty_blockly)
  %link{href: "#{blockly_path}css/common.css", rel: 'stylesheet', type: 'text/css'}
  %link{href: "#{blockly_path}css/#{app}.css", rel: 'stylesheet', type: 'text/css'}

  - if @game.name == "MazeEC" || @game.name == "ArtistEC" || @game.name == "Webapp"
    %script{src: "#{blockly_path}js/jsinterpreter/acorn_interpreter.js"}
    %script{src: "#{blockly_path}js/requirejs/require.js"}
    %script{src: "#{blockly_path}js/ace/ace.js"}
    %script{src: "#{blockly_path}js/ace/ext-language_tools.js"}
    %script{src: "#{blockly_path}js/droplet/droplet-full.min.js"}
    %link{href: "#{blockly_path}css/droplet/droplet.min.css", rel: 'stylesheet', type: 'text/css'}
  - else
    %script{src: "#{blockly_path}js/#{js_locale}/vendor.js"}
  %script{src: "#{blockly_path}js/#{js_locale}/#{app}#{pretty ? '' : '.min'}.js"}

  -# Create level options object to pass to Blockly
  - level, app_options = blockly_options(local_assigns)

  - if @autoplay_video_info
    :javascript
      showVideoDialog(#{@autoplay_video_info.to_json})

  -# use local[:symbol] to access locals passed into this render partial (defaults to false if not present)
  - local = Hash.new(false).merge!(local_assigns.delete_if{|_,v|v.nil?})

  - send_to_phone = request.location.try(:country_code) == 'US' ||              |
      (!Rails.env.production? && request.location.try(:country_code) == 'RD') |

  :javascript
    var script_path = "#{@script_level && build_script_level_path(@script_level)}";
    startTiming('Puzzle', script_path, '');
    var level = #{level.to_json};
    // Turn string values into functions for keys that begin with 'fn_' (JSON can't contain function definitions)
    // E.g. { fn_example: 'function () { return; }' } becomes { example: function () { return; } }
    (function fixUpFunctions(node) {
      if (typeof node !== 'object') return;
      for (var i in node) {
        if (/^fn_/.test(i)) {
          try {
            node[i.replace(/^fn_/, '')] = eval('(' + node[i] + ')');
          } catch (e) { }
        } else {
          fixUpFunctions(node[i]);
        }
      }
    })(level);
    // See assets/javascripts/sendReport for definition of lastServerResponse
    var appOptions = {
      levelId: '#{@level.level_num}',
      #{ "level_source_id: #{@level_source_id}," if @level_source_id }
      #{ "send_to_phone_url: '#{@phone_share_url}'," if @phone_share_url }
      #{ "sendToPhone: true," if send_to_phone}
      #{ "disableSocialShare: true," if @current_user && @current_user.under_13? }
      #{ "scriptId: '#{@script.id}'," if @script }
      #{ "levelGameName: '#{@level.game.name}'," if @level.game }
      level: level,
      #{ "skinId: '#{@level.skin}'," if @level.is_a?(Blockly) }
      callouts: #{@callouts.to_json} || [],
      createCallouts: function() {
        $.fn.qtip.zindex = 500;
        this.callouts.every(function(callout) {
          var selector = callout.element_id; // jquery selector.
          if ($(selector).length <= 0) { console.log("Couldn't find callout target."); return true;}

          var defaultConfig = {
            content: {
              text: callout.localized_text,
              title: {
                button: $('<div class="tooltip-x-close"/>').append($('<img src="#{asset_path 'x_button.png'}"/>'))
              }
            },
            style: {
              classes: "",
              tip: {
                width: 20,
                height: 20
              }
            },
            position: {
              my: "bottom left",
              at: "top right"
            },
            hide: {
              event: 'click mousedown touchstart'
            },
            show: false // don't show on mouseover
          };

          var customConfig = $.parseJSON(callout.qtip_config);
          var config = $.extend(true, {}, defaultConfig, customConfig);
          config.style.classes = config.style.classes.concat(" cdo-qtips");

          var calloutDomElement = $(selector).qtip(config);
          calloutDomElement.qtip('show');

          return true;
        });
      },
      onInitialize: function() {
        this.createCallouts();
        onInitializeListeners.forEach(function(listener) {
          listener();
        });
        #{render(partial: 'levels/chrome34Fix', formats: :js) if browser.chrome? && browser.version.to_s.to_i == 34}
      },
      locale: '#{js_locale}',
      containerId: 'blocklyApp',
      baseUrl: '#{blockly_path}',
      cacheBust: '#{blockly_cache_bust}',
      onAttempt: function(report) {
        report.fallbackResponse = #{@fallback_response.to_json};
        report.callback = '#{@callback}';
        if (#{@artist_builder.to_json}) {
          $('#builder-error').text('');
          ['program', 'name', 'instructions', 'type'].forEach(function(key) {
            report['level[' + key + ']'] = report[key];
          });
          delete report.level;
          report.onComplete = function(response) {
            if(lastServerResponse.nextRedirect) {
              window.location.href = lastServerResponse.nextRedirect;
            } else {
              $('#builder-error').text(lastServerResponse.report_error);
            }
          };
        }
        // Track puzzle attempt event
        trackEvent('Puzzle', 'Attempt', script_path, report.pass ? 1 : 0);
        if (report.pass) {
          trackEvent('Puzzle', 'Success', script_path, report.attempt);
          stopTiming('Puzzle', script_path, '');
        }
        trackEvent('Activity', 'Lines of Code', script_path, report.lines);
        sendReport(report);
      },
      onResetPressed: function() {
        cancelReport();
      },
      onContinue: function() {
        if (lastServerResponse.videoInfo) {
          showVideoDialog(lastServerResponse.videoInfo);
        } else if (lastServerResponse.nextRedirect) {
          window.location.href = lastServerResponse.nextRedirect;
        }
      },
      backToPreviousLevel: function() {
        if (lastServerResponse.previousLevelRedirect) {
          window.location.href = lastServerResponse.previousLevelRedirect;
        }
      },
      Dialog: Dialog,
      referenceArea: function() {
        var referenceDiv = $('#{escape_javascript(render partial: "levels/reference_area")}');
        referenceDiv.find('.video_link').each(function() {
          addClickTouchEvent($(this), $.proxy(function() {
            showVideoDialog({
              src: $(this).attr('data-src'),
              name: $(this).attr('data-name'),
              key: $(this).attr('data-key'),
              download: $(this).attr('data-download'),
              thumbnail: $(this).attr('data-thumbnail'),
              enable_fallback: true,
              autoplay: true
            });
          }, this));
        });
        return referenceDiv[0];
      },
      showInstructionsWrapper: function(showInstructions) {
        var hasInstructions = level.instructions || level.aniGifURL;
        if (!hasInstructions || this.share || level.skipInstructionsPopup) {
          return;
        }

        if ('#{@autoplay_video_info}') {
          $('.video-modal').on('hidden.bs.modal', function () {
            showInstructions();
          });
        } else {
          showInstructions();
        }
      },
      hide_source: #{local[:hide_source]},
      share: #{local[:share]},
      no_padding: #{local[:no_padding]},
      position: { blockYCoordinateInterval: 25 }
    };
    $.extend(appOptions, #{app_options.to_json});
    #{'console.log(appOptions)' unless Rails.env.production?};
    #{app}Main(appOptions);

dashboard/app/views/levels/_form.html.haml
= form_for [@level], method: @level.new_record? ? :post : :patch, remote: true do |f|
  = f.hidden_field :type, value: @type_class.to_s.presence || @level.type
  .field
    = f.label :name
    = f.text_field :name, placeholder: 'Level Name'
  - unless @level.new_record? && (@level.is_a?(Grid) || @level.is_a?(Calc) || @level.is_a?(Eval))
    .field
      = f.label 'concepts'
      %p
        Select
        %a.select_all{href: '#'} all
        \/
        %a.select_none{href: '#'} none
        (shift-click or cmd-click to select multiple).
      = f.collection_select :concept_ids, Concept.cached, :id, :name, { :selected => @level.concept_ids }, { :multiple => true, :name => 'level[concept_ids][]', :size => Concept.cached.length }
    = render partial: 'levels/editors/video', locals: {f: f}
    = render partial: 'levels/editors/blockly', locals: {f: f} if @level.is_a? Blockly
    = render partial: 'levels/editors/studio', locals: {f: f} if @level.is_a? Studio
    = render partial: 'levels/editors/maze', locals: {f: f} if @level.is_a? Maze
    = render partial: 'levels/editors/grid', locals: {f: f} if @level.is_a? Grid
    = render partial: 'levels/editors/karel', locals: {f: f} if @level.is_a? Karel
    = render partial: 'levels/editors/artist', locals: {f: f} if @level.is_a? Artist
    = render partial: 'levels/editors/dsl', locals: {f: f} if @level.is_a? DSLDefined
  .actions
    = f.submit
#validation-error
  - if @level.errors.any?
    %h2
      = pluralize(@level.errors.count, "error")
      prohibited this level from being saved:
    %ul
      - @level.errors.full_messages.each do |msg|
        %li= msg
:javascript
  #{render partial: 'shared/ajax_submit', formats: [:js],  locals: {form_selector: @level.new_record? ? '#new_level' : '.edit_level'}}
  function make_selection_handler(flag) {
    return function (e) {
      e.preventDefault();
      $(this).parent().siblings('select').children('option')[flag ? 'attr' : 'removeAttr']('selected', true);
    }
  }
  $('.select_all').click(make_selection_handler(true));
  $('.select_none').click(make_selection_handler(false));

dashboard/app/views/levels/_list.html.haml
%h1 Levels
%table
  %thead
    %tr
      %th{ width:100 } Levels
      %th{ width:100 } Game
      %th{ width:100 } URL
      %th{ width:300 }
  %tbody
    - @levels.each do |level|
      %tr
        %td= level.name
        %td= level.game.name if level.game
        %td= level.level_url if level.is_a? Blockly
        %td
          = link_to t('crud.show'), level
          - if can? :update, level
            = link_to t('crud.edit'), edit_level_path(level)
          - if can? :destroy, level
            = link_to t('crud.destroy'), level, method: :delete, data: { confirm: t('crud.confirm') }
          - if can? :create, Level
            = link_to 'Clone', level_clone_path(level), method: :post
%br/
- if can? :create, Level
  = link_to t('crud.new_model', model: Level.model_name.human), new_level_path

dashboard/app/views/levels/edit.html.haml
%h1 #{@level.new_record? ? 'New' : 'Editing'} #{@level.class.to_s} level
= render 'form'
= link_to t('crud.show'), @level
|
= link_to t('crud.back'), levels_path
= '|' unless @level.new_record?
= link_to t('crud.destroy'), @level, method: :delete, data: { confirm: t('crud.confirm') } unless @level.new_record?

dashboard/app/views/levels/index.html.haml
= render partial: 'levels/list'

dashboard/app/views/levels/new.html.haml
%h2 Choose a type of level to build

%ul
  %li= link_to "Script and Level builder how to", "https://docs.google.com/a/code.org/document/d/1HcYloRHibxk0Axnuw3A3w_Ht3AEmBHO0IUCaYFfs838/edit?usp=sharing"
  %li= link_to "Build a Maze Level", levels_new_path(type: "Maze")
  %li= link_to "Build a Farmer/Bee Level", levels_new_path(type: "Karel")
  %li= link_to "Build an Artist Level", levels_new_path(type: "Artist")
  %li= link_to "Build a Studio Level", levels_new_path(type: "Studio")
  %li= link_to "Build a Calc Level", levels_new_path(type: "Calc")
  %li= link_to "Build an Eval Level", levels_new_path(type: "Eval")
  %li= link_to "Build a Multi Level", levels_new_path(type: "Multi")
  %li= link_to "Build a Match Level", levels_new_path(type: "Match")
  %li= link_to "Build a Text Match Level", levels_new_path(type: "TextMatch")

%h3 Your Levels
- @levels.each do |level|
  %li
    = level.name
    = link_to t('crud.show'), level_path(level)
    = link_to t('crud.edit'), edit_level_path(level)
    = link_to t('crud.delete'), level_path(level, redirect: levels_new_path), method: :delete
    = link_to 'Clone', level_clone_path(level), method: :post

%h3 All levels
%ul
  %li
    = link_to "All non-artist levels", Game.find_by_name('CustomMaze')
  %li
    = link_to "All artist levels", Game.find_by_name('Custom')